AllCops:
  Exclude:
    - spec/**/*
StringLiterals:
  Enabled: false

WordArray:
  Enabled: false

LineLength:
  Enabled: false

Documentation:
  Enabled: false

TrailingBlankLines:
  Enabled: false

SpaceAfterComma:
  Enabled: false